server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: users-status-check
        uri: lb://users-ws
        predicates:
        - Path=/users/check/status
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
#        - RewritePath=/users-ws/(?<segment>.*, /$\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8010/eureka

      