spring:
  application:
    name: configserver
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/rajendramani-r/configserver.git
          username: rajendramani.r@gmail.com
          password: ARRMani@1489

server:
  port: 8013
  
token:
  expiration_time: 9000000000

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"