server:
  port: ${PORT:0}

gatewayIP : 192.168.1.40

token:
  expiration_time: 864000000
  secret: asd9a09asdas90d9as0d9q039eq2

login:
  url:
    path: /users/login

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/baasdb
    username: root
    password: Password123#@!
    initialization-mode: never
    hikari:
      maximum-pool-size: 10
      auto-commit: true
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5KB
      max-file-size: 5MB
      max-request-size: 6MB
      
logging:
  file: logs/userservice.log
  pattern:
    console: "%d [%level] %c{1.} [%t] %m%n"
    file: "%d [%level] %c{1.} [%t] %m%n"
  level:
    roor: info
    com.baas.userservice.*: debug
    org.springframework.web: error
    org.hibernate: error
 

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8010/eureka

    
  
#MySQL DEFAULT PWD: root - insert_password
