server:
  port: 8080

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/baasdb
    username: root
    password: Password123#@!
    initialization-mode: never
    hikari:
      maximum-pool-size: 10
      auto-commit: true
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8010/eureka

logging:
  level:
    corg.springframework: ERROR
    com.baas: DEBUG
    com.baas.*: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  file: log/userservice.log
  
#MySQL DEFAULT PWD: root - insert_password
