server:
  port: 8012

gateway:
  ip: 192.168.29.133

token:
  expiration_time: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739

login:
  url:
    path: /users/login

spring:
  cloud:
    config:
      uri: http://localhost:8013
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/backend
    username: root
    password: root
    initialization-mode: never
    hikari:
      maximum-pool-size: 10
      auto-commit: true
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5KB
      max-file-size: 5MB
      max-request-size: 6MB
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true
              
albums:
  url: http://albums-ws/users/%s/albums
  
resilience4j:
  circuitbreaker:
    instances:
      albums-ws:
        registerHealthIndicator: true
        slidingWindowSize: 2
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

logging:
  file:
    name: users-ws.log  
        #MySQL DEFAULT PWD: root - insert_password
