server:
  port: 8012

gateway:
  ip: 192.168.29.133

token:
  expiration_time: 864000000
  secret: hfgry463hf746hf573ydh475fhy5739

login:
  url:
    path: /users/login

spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/backend
    username: root
    password: root
    initialization-mode: never
    hikari:
      maximum-pool-size: 10
      auto-commit: true
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5KB
      max-file-size: 5MB
      max-request-size: 6MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

    
  
#MySQL DEFAULT PWD: root - insert_password
