server:
  port: ${PORT:0}

spring:
  application:
    name: albums-ws
  devtools:
    restart:
      enabled: true
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file:
    name: albums-ws.log